In [1]:
import numpy as np
import matplotlib.pyplot as plt
import keras 

from keras.datasets import mnist  
from keras.models import Sequential 
from keras.layers import Dense, Conv2D, MaxPool2D, Flatten, Dropout 

In [4]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [6]:
X_train = X_train.astype(np.float32)/255
X_test = X_test.astype(np.float32)/255


In [7]:
X_train = np.expand_dims(X_train, -1)
X_test = np.expand_dims(X_test, -1)

y_test = keras.utils.to_categorical(y_test)
y_train = keras.utils.to_categorical(y_train)

In [9]:
model = Sequential()
model.add(Conv2D(32, (3,3), input_shape=(28,28,1),activation='relu'))
model.add(MaxPool2D((2,2)))
model.add(Conv2D(64, (3,3), activation='relu'))
model.add(MaxPool2D((2,2)))
model.add(Flatten())
model.add(Dropout(0.25))
model.add(Dense(10,activation='softmax'))

c:\Program Files\Python312\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [10]:
model.compile(optimizer='adam',loss=keras.losses.categorical_crossentropy, metrics=['accuracy'])

In [ ]:
from keras.callbacks import EarlyStopping, ModelCheckpoint 

es = EarlyStopping(monitor='val_accuracy', min_delta=0.01, patience=4, verbose=1, mode='max')
mc = ModelCheckpoint("./bestmodel.h5", monitor='val_accuracy', verbose=1, save_best_only=True, mode='max')


cb = [es,mc]

history = model.fit(X_train,y_train,epochs=50, validation_split=0.3 ,callbacks=cb)

In [ ]:
model_s = keras.models.load_model("F:\COding\Code\##Coursera\ML\Practice_Code\Handwritten Digit Recog/bestmodel.h5")

In [14]:
y_pred = model_s.predict(X_test)
y_pred, y_test

313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step


(array([[8.80577208e-11, 2.97182190e-09, 2.46003850e-07, ...,
         9.99995947e-01, 1.84683080e-09, 3.77007922e-07],
        [6.17050091e-07, 6.67265226e-07, 9.99987841e-01, ...,
         6.93281127e-11, 9.97454754e-06, 2.37041750e-13],
        [9.66274705e-09, 9.99895573e-01, 1.24566455e-07, ...,
         7.28338682e-06, 3.59704302e-07, 6.07909314e-08],
        ...,
        [1.56842787e-14, 5.88254001e-10, 2.44810032e-13, ...,
         7.74971642e-09, 7.97876254e-09, 9.36243172e-09],
        [3.14529075e-07, 4.73981054e-12, 8.38830463e-11, ...,
         1.09153745e-11, 1.36521843e-03, 8.95035868e-08],
        [9.88743807e-08, 2.16940049e-10, 5.32962758e-06, ...,
         7.96155676e-12, 4.66323172e-06, 1.36018952e-09]], dtype=float32),
 array([[0., 0., 0., ..., 1., 0., 0.],
        [0., 0., 1., ..., 0., 0., 0.],
        [0., 1., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]))

In [15]:


# Predicted class labels (integers)
y_pred_classes = np.argmax(y_pred, axis=1)

# True class labels (integers)
y_true_classes = np.argmax(y_test, axis=1)

print(y_pred_classes[:10])  # first 10 predicted labels
print(y_true_classes[:10])  # first 10 true labels


[7 2 1 0 4 1 4 9 5 9]
[7 2 1 0 4 1 4 9 5 9]
